Vagrant.configure("2") do |config|
  # Box base: Debian 12
  config.vm.box = "debian/bookworm64"

  # Recursos de la VM
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"   # 2GB RAM
    vb.cpus = 2          # 2 cores 
  end

  # Disco extra de 20GB (además del que trae el box base)
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["createhd", "--filename", "extra_disk.vdi", "--size", 20480] # MB
    vb.customize ["storageattach", :id, "--storagectl", "SATA Controller",
                  "--port", 1, "--device", 0, "--type", "hdd", "--medium", "extra_disk.vdi"]
  end

  # Provisión mínima de paquetes
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y vim htop curl net-tools
    useradd -m -s /bin/bash developer
    echo "developer:developer" | chpasswd
    usermod -aG sudo developer
  SHELL
end


#Para practicar eso podés usar herramientas como fdisk, cfdisk o parted dentro de la VM. Cada vez que lo quieras resetear, basta con:

# vagrant destroy -f && vagrant up

# Usuarios que vienen por defecto en un box de Debian (ej. debian/bookworm64)
# root → existe, pero no tiene contraseña configurada (deshabilitado para login directo por SSH).
# vagrant → usuario creado para Vagrant:
# puede entrar por vagrant ssh

